#
# local authority map
#
{{- with .Values.application.gmsID }}
ivo://ivoa.net/std/GMS#search-1.0 = {{ . }}
ivo://ivoa.net/std/GMS#search-0.1 = {{ . }}
ivo://ivoa.net/std/GMS#users-1.0 = {{ . }}
ivo://ivoa.net/std/UMS#users-0.1 = {{ . }}
ivo://ivoa.net/std/UMS#users-1.0 = {{ . }}
ivo://ivoa.net/sso#tls-with-password = {{ . }}
{{- end }}
{{- with .Values.application.oidcURI }}
ivo://ivoa.net/sso#OAuth = {{ . }}
ivo://ivoa.net/sso#OpenID = {{ . }}
{{- end }}

{{- $raw := .Values.application.registryURL -}}
{{- $urls := ternary (list $raw) $raw (kindIs "string" $raw) -}}
{{- range $urls }}
ca.nrc.cadc.reg.client.RegistryClient.baseURL = {{ . }}
{{- end }}
