ca.nrc.cadc.doi.vospaceParentUri = {{ .Values.application.config.vospaceParentUri | required ".Values.application.config.vospaceParentUri is required" }}
ca.nrc.cadc.doi.landingUrl = {{ .Values.application.config.landingUrl | required ".Values.application.config.landingUrl is required" }}
ca.nrc.cadc.doi.datacite.mdsUrl = {{ .Values.application.config.mdsUrl | required ".Values.application.config.mdsUrl is required" }}
ca.nrc.cadc.doi.datacite.accountPrefix = {{ .Values.application.config.accountPrefix | required ".Values.application.config.accountPrefix is required" }}
{{- with .Values.application.config.metaDataPrefix }}
ca.nrc.cadc.doi.metaDataPrefix = {{ . }}
{{- end }}
{{- with .Values.application.config.groupPrefix }}
ca.nrc.cadc.doi.groupPrefix = {{ . }}
{{- end }}
{{- with .Values.application.config.doiIdentifierPrefix }}
ca.nrc.cadc.doi.doiIdentifierPrefix = {{ . }}
{{- end }}
{{- with .Values.application.config.publisherGroupURI }}
ca.nrc.cadc.doi.publisherGroupURI = {{ . }}
{{- end }}
{{- with .Values.application.config.selfPublish }}
ca.nrc.cadc.doi.selfPublish = {{ . }}
{{- end }}
{{- if .Values.application.config.randomTestID }}
ca.nrc.cadc.doi.randomTestID = true
{{- end }}
# ca.nrc.cadc.doi.datacite.username and ca.nrc.cadc.doi.datacite.password are appended at pod startup from Secret {{ include "doi.dataciteAuthSecretName" . }}.
