ca.nrc.cadc.doi.vospaceParentUri = {{ .Values.deployment.doi.config.vospaceParentUri | required ".Values.deployment.doi.config.vospaceParentUri is required" }}
ca.nrc.cadc.doi.metaDataPrefix = {{ .Values.deployment.doi.config.metaDataPrefix | required ".Values.deployment.doi.config.metaDataPrefix is required" }}
ca.nrc.cadc.doi.groupPrefix = {{ .Values.deployment.doi.config.groupPrefix | required ".Values.deployment.doi.config.groupPrefix is required" }}
ca.nrc.cadc.doi.landingUrl = {{ .Values.deployment.doi.config.landingUrl | required ".Values.deployment.doi.config.landingUrl is required" }}
ca.nrc.cadc.doi.datacite.mdsUrl = {{ .Values.deployment.doi.config.mdsUrl | required ".Values.deployment.doi.config.mdsUrl is required" }}
ca.nrc.cadc.doi.datacite.accountPrefix = {{ .Values.deployment.doi.config.accountPrefix | required ".Values.deployment.doi.config.accountPrefix is required" }}
{{- with .Values.deployment.doi.config.doiIdentifierPrefix }}
ca.nrc.cadc.doi.doiIdentifierPrefix = {{ . }}
{{- end }}
{{- with .Values.deployment.doi.config.publisherGroupURI }}
ca.nrc.cadc.doi.publisherGroupURI = {{ . }}
{{- end }}
{{- with .Values.deployment.doi.config.selfPublish }}
ca.nrc.cadc.doi.selfPublish = {{ . }}
{{- end }}
{{- if .Values.deployment.doi.config.randomTestID }}
ca.nrc.cadc.doi.randomTestID = true
{{- end }}
# ca.nrc.cadc.doi.datacite.username and ca.nrc.cadc.doi.datacite.password are appended at pod startup from Secret {{ include "doi.dataciteAuthSecretName" . }}.
