version: '3.8'

# RAFTS Docker Swarm Stack
# Deploy: docker stack deploy -c rafts-stack.yml rafts
# Remove: docker stack rm rafts

services:
  # =============================================================================
  # rafts-frontend - Next.js Application
  # =============================================================================
  rafts-frontend:
    image: ${RAFTS_FRONTEND_IMAGE:-bucket.canfar.net/rafts-frontend:latest}
    environment:
      NODE_ENV: 'production'
      PORT: '8080'
      NEXTAUTH_URL_INTERNAL: 'http://rafts-frontend:8080'
      VALIDATOR_URL_XML: 'http://rafts-ades-validator:8080/validate-xml'
      VALIDATOR_URL_PSV: 'http://rafts-ades-validator:8080/validate-psv'
      VALIDATOR_URL_MPC: 'http://rafts-ades-validator:8080/validate-mpc'
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: ingress
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'http://127.0.0.1:8080/api/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - rafts-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 5s
        order: start-first
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  # =============================================================================
  # rafts-ades-validator - ADES Validation Service
  # =============================================================================
  rafts-ades-validator:
    image: ${ADES_VALIDATOR_IMAGE:-bucket.canfar.net/ades-validator-api:latest}
    healthcheck:
      test:
        [
          'CMD',
          'python',
          '-c',
          "import urllib.request; urllib.request.urlopen('http://localhost:8080/health-check')",
        ]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - rafts-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 5s
        order: start-first
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M

networks:
  rafts-network:
    driver: overlay
