apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "citation.fullname" . }}-config
  labels:
    {{- include "citation.labels" . | nindent 4 }}
data:
  # Properties required by cadc-tomcat server.xml Connector configuration.
  # See: https://github.com/opencadc/docker-base/blob/main/cadc-tomcat/src/server.xml
  catalina.properties: |-
    tomcat.connector.connectionTimeout={{ include "citation.tomcatConnectorConnectionTimeout" . }}
    tomcat.connector.keepAliveTimeout={{ include "citation.tomcatConnectorKeepAliveTimeout" . }}
    tomcat.connector.secure={{ include "citation.tomcatConnectorSecure" . }}
    tomcat.connector.scheme={{ include "citation.tomcatConnectorScheme" . }}
    tomcat.connector.proxyName={{ include "citation.tomcatConnectorProxyName" . }}
    tomcat.connector.proxyPort={{ include "citation.tomcatConnectorProxyPort" . }}
