# Dockerfile.dev
FROM node:22-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./

RUN npm install

# Copy source code
COPY . .

# Expose port 3000 for Next.js
EXPOSE 3000

CMD ["npm", "run", "dev"]
